name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

         # Set up environment file
    - name: Set environment variables
      run: echo "OUTPUT_VAR=value" >> $GITHUB_ENV

        
    # Read environment file in another step
    - name: Read environment variables
      run: |
        echo "Output variable is $OUTPUT_VAR"
